### ISSUE TITLE
Getting " Forbidden - a valid `x-typesense-api-key` header must be sent." from python client but not javascript client with same credentials

### ISSUE THREAD

**Issue by SimonShapiro** [typesense/typesense-python#21]
## Description

Strangely, i am getting invalid api-key from the python client, but not from the javascript client.

## Steps to reproduce

I have included the link to a gist below.

(https://gist.github.com/SimonShapiro/1f6b8ffee770a9c2b655f41d9c019257)

## Expected Behavior

A list of collections.

## Actual Behavior

```
{'api_key': 'ko82LtPj0ChYNPV6rQtldoQgPJMNnQSt', 'nodes': [{'host': '6jbsua10yct5odk3p-1.a1.typesense.net', 'port': '443', 'protocol': 'https'}], 'connection_timeout_seconds': 2}
Traceback (most recent call last):
  File "/Users/simonshapiro/typsense_issue/gist.py", line 20, in <module>
    retrieve_all_response = client.collections.retrieve()
  File "/Users/simonshapiro/typsense_issue/thisPython/lib/python3.7/site-packages/typesense/collections.py", line 21, in retrieve
    return self.api_call.get('{0}'.format(Collections.RESOURCE_PATH))
  File "/Users/simonshapiro/typsense_issue/thisPython/lib/python3.7/site-packages/typesense/api_call.py", line 137, in get
    timeout=self.config.connection_timeout_seconds)
  File "/Users/simonshapiro/typsense_issue/thisPython/lib/python3.7/site-packages/typesense/api_call.py", line 113, in make_request
    raise ApiCall.get_exception(r.status_code)(r.status_code, error_message)
typesense.exceptions.RequestUnauthorized: [Errno 401] Forbidden - a valid `x-typesense-api-key` header must be sent.

```

## Metadata

**Typsense Version**:

hosted cloud

**OS**:

macos 12.4

**Comment by SimonShapiro** [comment]
Even yierder;  I generated a new api_ky and it started working along with the others?

**Comment by kishorenc** [comment]
Could it be because you were using a search API key with the JS client, while Python client operations require a key with write permission?
