### ISSUE TITLE
AttributeError: partially initialized module 'typesense' has no attribute 'Client' (most likely due to a circular import)

### ISSUE THREAD

**Issue by sahuguet** [typesense/typesense-python#23]
## Description
Cannot install Python package: 'typesense' has no attribute 'Client'

```
% python
Python 3.9.9 (main, Dec  5 2021, 23:37:58)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import typesense
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/typesense.py", line 3, in <module>
    client = typesense.Client({
AttributeError: partially initialized module 'typesense' has no attribute 'Client' (most likely due to a circular import)
```

## Steps to reproduce
- install typesense using `pip install`
-  run Python and import

## Expected Behavior
Successful `import` statement.

## Metadata

**Typsense Version**:
typesense==0.14.0

**OS**:
Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

**Comment by sahuguet** [comment]
My Python file was named `typesense.py` in the working directory, which created the conflict.
